// <auto-generated />
namespace SalaryApp.DataLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addpay_Idandworkgroup_IdtoSalaryPayDetailsentity : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addpay_Idandworkgroup_IdtoSalaryPayDetailsentity));
        
        string IMigrationMetadata.Id
        {
            get { return "201909122005509_add pay_Id and workgroup_Id to SalaryPayDetails entity."; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
