// <auto-generated />
namespace SalaryApp.DataLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class makepaytype_Idworkshop_IdFinancital_Idinpayeneity : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(makepaytype_Idworkshop_IdFinancital_Idinpayeneity));
        
        string IMigrationMetadata.Id
        {
            get { return "201909091834551_make paytype_Id workshop_Id,Financital_Id in pay eneity."; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
