// <auto-generated />
namespace SalaryApp.DataLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class makepaytype_IdandWOrkshop_Idinpayentity : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(makepaytype_IdandWOrkshop_Idinpayentity));
        
        string IMigrationMetadata.Id
        {
            get { return "201909091223086_make paytype_Id and WOrkshop_Id in pay entity"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
